#!/usr/bin/env python3
"""
Match RGB and depth index files in a TUM-like RGB-D sequence.

By default this script:
- reads rgb.txt and depth.txt
- matches entries by nearest timestamp within a tolerance
- writes matched_rgb.txt and matched_depth.txt
- leaves original files untouched

Optional flags can:
- overwrite rgb.txt / depth.txt
- copy only matched image files into a new output directory
"""

import argparse
import os
import shutil
from dataclasses import dataclass


HEADER_LINES = [
    "# RGB-D matched index",
    "# timestamp filename",
    "# generated by match_tum_rgb_depth.py",
]


@dataclass
class Entry:
    timestamp: float
    relpath: str


def parse_args():
    parser = argparse.ArgumentParser(description="Match TUM-like rgb.txt and depth.txt")
    parser.add_argument("sequence_dir", type=str, help="Path to a sequence directory")
    parser.add_argument(
        "--tolerance",
        type=float,
        default=0.03,
        help="Maximum timestamp difference in seconds for matching (default: 0.03)",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite rgb.txt and depth.txt with the matched indices",
    )
    parser.add_argument(
        "--copy-matched",
        action="store_true",
        help="Copy matched files into <sequence_dir>_matched",
    )
    return parser.parse_args()


def read_index_file(path):
    entries = []
    with open(path, "r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(maxsplit=1)
            if len(parts) != 2:
                continue
            entries.append(Entry(timestamp=float(parts[0]), relpath=parts[1]))
    return entries


def write_index_file(path, entries):
    with open(path, "w", encoding="utf-8") as handle:
        for line in HEADER_LINES:
            handle.write(line + "\n")
        for entry in entries:
            handle.write(f"{entry.timestamp:.6f} {entry.relpath}\n")


def nearest_match(rgb_entries, depth_entries, tolerance):
    matches = []
    used_depth = set()
    depth_ts = [entry.timestamp for entry in depth_entries]

    j = 0
    for rgb_entry in rgb_entries:
        while j + 1 < len(depth_entries) and depth_ts[j + 1] <= rgb_entry.timestamp:
            j += 1

        candidates = []
        if j < len(depth_entries):
            candidates.append(j)
        if j - 1 >= 0:
            candidates.append(j - 1)
        if j + 1 < len(depth_entries):
            candidates.append(j + 1)

        best_idx = None
        best_dt = None
        for idx in candidates:
            if idx in used_depth:
                continue
            dt = abs(depth_entries[idx].timestamp - rgb_entry.timestamp)
            if best_dt is None or dt < best_dt:
                best_dt = dt
                best_idx = idx

        if best_idx is not None and best_dt is not None and best_dt <= tolerance:
            used_depth.add(best_idx)
            depth_entry = depth_entries[best_idx]
            matches.append(
                (
                    Entry(timestamp=rgb_entry.timestamp, relpath=rgb_entry.relpath),
                    Entry(timestamp=rgb_entry.timestamp, relpath=depth_entry.relpath),
                )
            )

    return matches


def ensure_parent(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)


def copy_matched_sequence(sequence_dir, matched_pairs):
    out_dir = sequence_dir.rstrip("/\\") + "_matched"
    rgb_dir = os.path.join(out_dir, "rgb")
    depth_dir = os.path.join(out_dir, "depth")
    os.makedirs(rgb_dir, exist_ok=True)
    os.makedirs(depth_dir, exist_ok=True)

    matched_rgb = []
    matched_depth = []

    for rgb_entry, depth_entry in matched_pairs:
        ts = rgb_entry.timestamp
        rgb_name = f"{ts:.6f}.png"
        depth_name = f"{ts:.6f}.png"

        rgb_src = os.path.join(sequence_dir, rgb_entry.relpath)
        depth_src = os.path.join(sequence_dir, depth_entry.relpath)
        rgb_dst_rel = os.path.join("rgb", rgb_name)
        depth_dst_rel = os.path.join("depth", depth_name)
        rgb_dst = os.path.join(out_dir, rgb_dst_rel)
        depth_dst = os.path.join(out_dir, depth_dst_rel)

        ensure_parent(rgb_dst)
        ensure_parent(depth_dst)
        shutil.copy2(rgb_src, rgb_dst)
        shutil.copy2(depth_src, depth_dst)

        matched_rgb.append(Entry(timestamp=ts, relpath=rgb_dst_rel))
        matched_depth.append(Entry(timestamp=ts, relpath=depth_dst_rel))

    write_index_file(os.path.join(out_dir, "rgb.txt"), matched_rgb)
    write_index_file(os.path.join(out_dir, "depth.txt"), matched_depth)

    for extra_name in ("intrinsics.txt", "metadata.txt", "arkit_pose.txt"):
        src = os.path.join(sequence_dir, extra_name)
        if os.path.exists(src):
            shutil.copy2(src, os.path.join(out_dir, extra_name))

    return out_dir


def main():
    args = parse_args()
    sequence_dir = os.path.abspath(args.sequence_dir)
    rgb_index_path = os.path.join(sequence_dir, "rgb.txt")
    depth_index_path = os.path.join(sequence_dir, "depth.txt")

    if not os.path.exists(rgb_index_path):
        raise FileNotFoundError(f"Missing file: {rgb_index_path}")
    if not os.path.exists(depth_index_path):
        raise FileNotFoundError(f"Missing file: {depth_index_path}")

    rgb_entries = read_index_file(rgb_index_path)
    depth_entries = read_index_file(depth_index_path)
    matches = nearest_match(rgb_entries, depth_entries, args.tolerance)

    matched_rgb = [pair[0] for pair in matches]
    matched_depth = [pair[1] for pair in matches]

    matched_rgb_path = os.path.join(sequence_dir, "matched_rgb.txt")
    matched_depth_path = os.path.join(sequence_dir, "matched_depth.txt")
    write_index_file(matched_rgb_path, matched_rgb)
    write_index_file(matched_depth_path, matched_depth)

    print(f"Sequence     : {sequence_dir}")
    print(f"RGB frames   : {len(rgb_entries)}")
    print(f"Depth frames : {len(depth_entries)}")
    print(f"Matched      : {len(matches)}")
    print(f"Tolerance    : {args.tolerance:.3f}s")
    print(f"Wrote        : {matched_rgb_path}")
    print(f"Wrote        : {matched_depth_path}")

    if args.overwrite:
        write_index_file(rgb_index_path, matched_rgb)
        write_index_file(depth_index_path, matched_depth)
        print("Overwrote original rgb.txt and depth.txt with matched indices")

    if args.copy_matched:
        out_dir = copy_matched_sequence(sequence_dir, matches)
        print(f"Copied matched sequence to: {out_dir}")


if __name__ == "__main__":
    main()