#!/usr/bin/env python3
"""Create a self-contained forward-then-reverse TUM RGB-D backtracking set.

The output frame order is ``0, 1, ..., N-1, N-1, ..., 1, 0``.  It uses a new,
strictly increasing timestamp sequence because COMO consumes a temporal stream.
Image/depth/confidence PNGs are hard-linked where possible (copied only when
hard links are unavailable), while all temporal index and ARKit-pose text files
are regenerated to match the new order.
"""

from __future__ import annotations

import argparse
import os
import shutil
from dataclasses import dataclass
from pathlib import Path


INDEX_HEADER = (
    "# COMO-ready TUM RGB-D index",
    "# timestamp filename",
    "# generated by make_tum_backtracking_sequence.py",
)


@dataclass(frozen=True)
class Record:
    timestamp: float
    rgb_relative: str
    depth_relative: str
    pose_values: tuple[str, ...]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="Source COMO-ready TUM dataset")
    parser.add_argument("--output", type=Path, required=True, help="New backtracking dataset")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate and report the sequence plan without creating an output directory.",
    )
    return parser.parse_args()


def read_index(path: Path) -> list[tuple[float, str]]:
    rows: list[tuple[float, str]] = []
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            timestamp_text, relative_path = line.split()
            rows.append((float(timestamp_text), relative_path))
    if not rows:
        raise ValueError(f"No frame rows in {path}")
    if any(second[0] <= first[0] for first, second in zip(rows, rows[1:])):
        raise ValueError(f"Timestamps must be strictly increasing in {path}")
    return rows


def read_arkit_poses(path: Path) -> dict[str, tuple[str, ...]]:
    poses: dict[str, tuple[str, ...]] = {}
    with path.open(encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            values = line.split()
            if len(values) != 8:
                raise ValueError(f"Expected 8 ARKit pose values, got {len(values)} in {path}")
            poses[f"{float(values[0]):.6f}"] = tuple(values[1:])
    return poses


def load_records(input_dir: Path) -> list[Record]:
    rgb_index = input_dir / "matched_rgb.txt"
    depth_index = input_dir / "matched_depth.txt"
    if not rgb_index.exists() or not depth_index.exists():
        raise FileNotFoundError("Source requires matched_rgb.txt and matched_depth.txt")
    rgb_rows = read_index(rgb_index)
    depth_rows = read_index(depth_index)
    if len(rgb_rows) != len(depth_rows):
        raise ValueError("RGB and depth index row counts differ")
    poses = read_arkit_poses(input_dir / "arkit_pose.txt")
    records: list[Record] = []
    for (rgb_timestamp, rgb_relative), (depth_timestamp, depth_relative) in zip(rgb_rows, depth_rows):
        if abs(rgb_timestamp - depth_timestamp) > 1e-6:
            raise ValueError(f"RGB/depth timestamp mismatch: {rgb_timestamp} vs {depth_timestamp}")
        timestamp_key = f"{rgb_timestamp:.6f}"
        if timestamp_key not in poses:
            raise ValueError(f"No matching ARKit pose for timestamp {timestamp_key}")
        for relative_path in (rgb_relative, depth_relative):
            if not (input_dir / relative_path).is_file():
                raise FileNotFoundError(f"Missing source frame: {input_dir / relative_path}")
        records.append(Record(rgb_timestamp, rgb_relative, depth_relative, poses[timestamp_key]))
    return records


def timestamped_records(records: list[Record]) -> list[tuple[float, Record]]:
    if len(records) < 2:
        raise ValueError("Backtracking requires at least two frames")
    step = float(sorted(record_b.timestamp - record_a.timestamp for record_a, record_b in zip(records, records[1:]))[len(records) // 2 - 1])
    if step <= 0:
        raise ValueError("Invalid source timestamp increment")
    ordered = records + list(reversed(records))
    output: list[tuple[float, Record]] = []
    # Preserve the original measured timing during the forward pass.  The
    # reverse pass begins one nominal frame interval after the original end.
    for index, record in enumerate(ordered):
        timestamp = record.timestamp if index < len(records) else records[-1].timestamp + (index - len(records) + 1) * step
        output.append((timestamp, record))
    return output


def write_index(path: Path, rows: list[tuple[float, str]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("\n".join(INDEX_HEADER) + "\n")
        for timestamp, relative_path in rows:
            handle.write(f"{timestamp:.6f} {relative_path}\n")


def link_or_copy(source: Path, destination: Path) -> None:
    destination.parent.mkdir(parents=True, exist_ok=True)
    try:
        os.link(source, destination)
    except OSError:
        shutil.copy2(source, destination)


def build_output(input_dir: Path, output_dir: Path, output_records: list[tuple[float, Record]]) -> None:
    if output_dir.exists():
        raise FileExistsError(f"Refusing to overwrite existing output directory: {output_dir}")
    output_dir.mkdir(parents=True)
    try:
        # Reuse one copy of each source image; the repeated reverse pass is
        # represented in the new temporal index, not by duplicate PNG files.
        for subdirectory in ("rgb", "depth", "confidence"):
            source_subdirectory = input_dir / subdirectory
            if not source_subdirectory.is_dir():
                if subdirectory == "confidence":
                    continue
                raise FileNotFoundError(f"Missing source directory: {source_subdirectory}")
            for source in source_subdirectory.iterdir():
                if source.is_file():
                    link_or_copy(source, output_dir / subdirectory / source.name)

        for filename in ("intrinsics.txt",):
            shutil.copy2(input_dir / filename, output_dir / filename)
        rgb_rows = [(timestamp, record.rgb_relative) for timestamp, record in output_records]
        depth_rows = [(timestamp, record.depth_relative) for timestamp, record in output_records]
        for filename, rows in (
            ("rgb.txt", rgb_rows),
            ("depth.txt", depth_rows),
            ("matched_rgb.txt", rgb_rows),
            ("matched_depth.txt", depth_rows),
        ):
            write_index(output_dir / filename, rows)
        with (output_dir / "arkit_pose.txt").open("w", encoding="utf-8") as handle:
            handle.write("# timestamp tx ty tz qx qy qz qw\n")
            for timestamp, record in output_records:
                handle.write(f"{timestamp:.6f} {' '.join(record.pose_values)}\n")

        source_metadata = (input_dir / "metadata.txt").read_text(encoding="utf-8")
        with (output_dir / "metadata.txt").open("w", encoding="utf-8") as handle:
            handle.write(source_metadata.rstrip() + "\n")
            handle.write("sequence_transform=forward_then_reverse_backtracking\n")
            handle.write(f"backtracking_source_dataset={input_dir}\n")
            handle.write(f"backtracking_source_frames={len(output_records) // 2}\n")
            handle.write(f"backtracking_output_frames={len(output_records)}\n")
            handle.write("backtracking_turnaround_frame_is_duplicated=true\n")
            handle.write("backtracking_files=hardlinked_or_copied; temporal_indexes_and_arkit_pose_regenerated\n")
    except Exception:
        shutil.rmtree(output_dir, ignore_errors=True)
        raise


def main() -> None:
    args = parse_args()
    input_dir = args.input.expanduser().resolve()
    output_dir = args.output.expanduser().resolve()
    records = load_records(input_dir)
    output_records = timestamped_records(records)
    print(
        f"source frames={len(records)}, output frames={len(output_records)}, "
        f"first={output_records[0][0]:.6f}, last={output_records[-1][0]:.6f}"
    )
    if args.dry_run:
        print("dry run: output was not created")
        return
    build_output(input_dir, output_dir, output_records)
    print(f"wrote: {output_dir}")


if __name__ == "__main__":
    main()
