#!/usr/bin/env python3
"""Convert one Stray Scanner iPhone LiDAR export to COMO's TUM RGB-D format.

The converter keeps RGB and depth at the native aligned depth resolution,
creates the TUM index files expected by COMO, and corrects Stray's millimetre
depth units for COMO's fixed ``depth_png / 5000`` loader convention.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import cv2
import numpy as np


INDEX_HEADER = (
    "# COMO-ready TUM RGB-D index",
    "# timestamp filename",
    "# generated by stray_scanner_to_tum.py",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, required=True, help="Stray export directory")
    parser.add_argument("--output", type=Path, required=True, help="New TUM output directory")
    parser.add_argument(
        "--target-fps",
        type=float,
        default=6.0,
        help="Temporal sampling rate; 0 retains every RGB-D frame (default: 6)",
    )
    parser.add_argument(
        "--min-confidence",
        type=int,
        choices=(0, 1, 2),
        default=0,
        help="Retain depth with at least this ARKit confidence value (default: 0, no filtering)",
    )
    parser.add_argument(
        "--device",
        default="iPhone 15 Pro Max",
        help="Device label stored in metadata.txt",
    )
    return parser.parse_args()


def require_input(input_dir: Path) -> None:
    required = (
        input_dir / "rgb.mp4",
        input_dir / "depth",
        input_dir / "confidence",
        input_dir / "camera_matrix.csv",
        input_dir / "odometry.csv",
    )
    missing = [str(path) for path in required if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing Stray Scanner input: " + ", ".join(missing))


def load_records(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        records = list(csv.DictReader(handle, skipinitialspace=True))
    required = {"timestamp", "frame", "x", "y", "z", "qx", "qy", "qz", "qw"}
    if not records or not required.issubset(records[0]):
        raise ValueError(f"Unexpected odometry columns in {path}")
    timestamps = [float(record["timestamp"]) for record in records]
    if any(b <= a for a, b in zip(timestamps, timestamps[1:])):
        raise ValueError("odometry timestamps must be strictly increasing")
    return records


def select_records(records: list[dict[str, str]], target_fps: float) -> list[dict[str, str]]:
    if target_fps == 0:
        return records
    if target_fps < 0:
        raise ValueError("--target-fps must be non-negative")
    period = 1.0 / target_fps
    selected = [records[0]]
    next_timestamp = float(records[0]["timestamp"]) + period
    for record in records[1:]:
        if float(record["timestamp"]) + 1e-9 >= next_timestamp:
            selected.append(record)
            next_timestamp = float(record["timestamp"]) + period
    return selected


def write_index(path: Path, entries: list[tuple[str, str]]) -> None:
    with path.open("w", encoding="utf-8") as handle:
        handle.write("\n".join(INDEX_HEADER) + "\n")
        for timestamp, filename in entries:
            handle.write(f"{timestamp} {filename}\n")


def main() -> None:
    args = parse_args()
    input_dir = args.input.expanduser().resolve()
    output_dir = args.output.expanduser().resolve()
    require_input(input_dir)
    if output_dir.exists():
        raise FileExistsError(f"Refusing to overwrite existing output directory: {output_dir}")

    records = load_records(input_dir / "odometry.csv")
    selected = select_records(records, args.target_fps)
    selected_frames = {record["frame"] for record in selected}
    last_selected_index = max(
        index for index, record in enumerate(records) if record["frame"] in selected_frames
    )

    cap = cv2.VideoCapture(str(input_dir / "rgb.mp4"))
    if not cap.isOpened():
        raise RuntimeError(f"Cannot open {input_dir / 'rgb.mp4'}")
    rgb_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    rgb_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    video_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    if video_frames != len(records):
        cap.release()
        raise ValueError(f"Video has {video_frames} frames but odometry has {len(records)} rows")

    first_depth_path = input_dir / "depth" / f"{records[0]['frame']}.png"
    first_depth = cv2.imread(str(first_depth_path), cv2.IMREAD_UNCHANGED)
    if first_depth is None or first_depth.dtype != np.uint16 or first_depth.ndim != 2:
        cap.release()
        raise ValueError(f"Invalid first depth frame: {first_depth_path}")
    depth_height, depth_width = first_depth.shape
    camera_matrix = np.loadtxt(input_dir / "camera_matrix.csv", delimiter=",")
    if camera_matrix.shape != (3, 3):
        cap.release()
        raise ValueError("camera_matrix.csv must contain a 3x3 matrix")
    camera_matrix /= camera_matrix[2, 2]
    sx, sy = depth_width / rgb_width, depth_height / rgb_height
    camera_matrix[0, (0, 2)] *= sx
    camera_matrix[1, (1, 2)] *= sy

    output_dir.mkdir(parents=True)
    rgb_dir = output_dir / "rgb"
    depth_dir = output_dir / "depth"
    confidence_dir = output_dir / "confidence"
    rgb_dir.mkdir()
    depth_dir.mkdir()
    confidence_dir.mkdir()

    rgb_entries: list[tuple[str, str]] = []
    depth_entries: list[tuple[str, str]] = []
    selected_records: list[dict[str, str]] = []
    confidence_zero_pixels = 0
    total_depth_pixels = 0
    try:
        for index, record in enumerate(records):
            if index > last_selected_index:
                break
            ok, rgb = cap.read()
            if not ok or rgb is None:
                raise RuntimeError(f"Could not decode RGB frame {index}")
            if record["frame"] not in selected_frames:
                continue

            depth = cv2.imread(
                str(input_dir / "depth" / f"{record['frame']}.png"), cv2.IMREAD_UNCHANGED
            )
            confidence = cv2.imread(
                str(input_dir / "confidence" / f"{record['frame']}.png"), cv2.IMREAD_UNCHANGED
            )
            if (
                depth is None
                or depth.shape != (depth_height, depth_width)
                or depth.dtype != np.uint16
                or confidence is None
                or confidence.shape != depth.shape
                or confidence.dtype != np.uint8
            ):
                raise ValueError(f"Invalid depth/confidence pair for source frame {record['frame']}")

            timestamp = f"{float(record['timestamp']):.6f}"
            # Stray values are millimetres.  COMO loads uint16 TUM PNG as
            # metres via depth_png / 5000, so 1 mm must be stored as 5.
            depth_out = np.minimum(
                depth.astype(np.uint32) * 5, np.iinfo(np.uint16).max
            ).astype(np.uint16)
            depth_out[confidence < args.min_confidence] = 0
            rgb_out = cv2.resize(rgb, (depth_width, depth_height), interpolation=cv2.INTER_AREA)
            rgb_relative = f"rgb/{timestamp}.png"
            depth_relative = f"depth/{timestamp}.png"
            confidence_relative = f"confidence/{timestamp}.png"
            if not cv2.imwrite(str(output_dir / rgb_relative), rgb_out):
                raise RuntimeError(f"Could not write {rgb_relative}")
            if not cv2.imwrite(str(output_dir / depth_relative), depth_out):
                raise RuntimeError(f"Could not write {depth_relative}")
            if not cv2.imwrite(str(output_dir / confidence_relative), confidence):
                raise RuntimeError(f"Could not write {confidence_relative}")
            rgb_entries.append((timestamp, rgb_relative))
            depth_entries.append((timestamp, depth_relative))
            selected_records.append(record)
            confidence_zero_pixels += int(np.count_nonzero(confidence == 0))
            total_depth_pixels += confidence.size
    except Exception:
        cap.release()
        raise
    cap.release()

    write_index(output_dir / "rgb.txt", rgb_entries)
    write_index(output_dir / "depth.txt", depth_entries)
    write_index(output_dir / "matched_rgb.txt", rgb_entries)
    write_index(output_dir / "matched_depth.txt", depth_entries)
    with (output_dir / "intrinsics.txt").open("w", encoding="utf-8") as handle:
        handle.write("# RGB camera intrinsics, scaled to the aligned depth resolution\n")
        handle.write("# width height fx fy cx cy\n")
        handle.write(
            f"{depth_width} {depth_height} {camera_matrix[0,0]:.6f} "
            f"{camera_matrix[1,1]:.6f} {camera_matrix[0,2]:.6f} {camera_matrix[1,2]:.6f}\n"
        )
        handle.write("# uint16 PNG depth divisor: depth_m = depth_png / divisor\n5000.0\n")
    with (output_dir / "arkit_pose.txt").open("w", encoding="utf-8") as handle:
        handle.write("# timestamp tx ty tz qx qy qz qw\n")
        for record in selected_records:
            fields = ("x", "y", "z", "qx", "qy", "qz", "qw")
            handle.write(
                f"{float(record['timestamp']):.6f} "
                + " ".join(f"{float(record[field]):.9g}" for field in fields)
                + "\n"
            )
    with (output_dir / "metadata.txt").open("w", encoding="utf-8") as handle:
        handle.write(f"device={args.device}\n")
        handle.write("recorder=Stray Scanner (ARKit)\n")
        handle.write("depth_source=ARKit LiDAR depth\n")
        handle.write(f"source_rgb_width={rgb_width}\nsource_rgb_height={rgb_height}\n")
        handle.write(f"rgb_width={depth_width}\nrgb_height={depth_height}\n")
        handle.write(f"depth_width={depth_width}\ndepth_height={depth_height}\n")
        handle.write("source_depth_units=millimetres\n")
        handle.write("depth_conversion=source_depth_png_x_5_for_como_divisor_5000\n")
        handle.write("depth_scale_factor=5000.0\n")
        handle.write(f"source_frames={len(records)}\noutput_frames={len(selected_records)}\n")
        handle.write(f"target_fps={args.target_fps}\n")
        handle.write(f"minimum_confidence={args.min_confidence}\n")
        handle.write(f"confidence_zero_fraction={confidence_zero_pixels / total_depth_pixels:.8f}\n")
        handle.write("pose_file=arkit_pose.txt\n")
        handle.write("note=ARKit poses are estimated, not motion-capture ground truth\n")

    print(f"wrote {len(selected_records)} RGB-D frames to {output_dir}")
    print(
        "intrinsics: "
        f"fx={camera_matrix[0,0]:.3f}, fy={camera_matrix[1,1]:.3f}, "
        f"cx={camera_matrix[0,2]:.3f}, cy={camera_matrix[1,2]:.3f}"
    )


if __name__ == "__main__":
    main()
